name: validate (lint) markdown files
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v5

      # NOTE: heavy node.js is used only to run markdownlint - the same tool as in my editor (Visual Studio Code)

      - name: install node.js (current LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: install markdownlint-cli
        run: sudo npm install -g markdownlint-cli

      - name: validate all markdown files
        run: cd "${{ github.workspace }}" && ./tests/run-markdownlint.sh
